# Generated by Django 4.1.7 on 2023-03-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0002_modify_workspace_adding_created_and_update_field'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workspace',
            table='workspace',
        ),
    ]
