# Generated by Django 4.1.7 on 2023-03-22 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0003_rename_workspace_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='progess',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
