# Generated by Django 4.1.7 on 2023-03-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0005_fix_spelling_progress_field_in_workspacetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
