# Generated by Django 4.1.7 on 2023-03-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0006_change_updated_from_date_to_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
