# Generated by Django 4.1.7 on 2023-03-28 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0008_make_field_updated_none_autoupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='workspace',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='progress',
        ),
        migrations.AddField(
            model_name='workspace',
            name='total_task_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
