# Generated by Django 4.1.7 on 2023-03-28 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0012_adding_related_name_in_workspace_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks_api.workspace'),
        ),
    ]
