# Generated by Django 4.1.7 on 2023-03-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0015_make_tasks_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks_api.workspace'),
        ),
    ]
