# Generated by Django 4.1.7 on 2023-03-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0017_set_on_delete_to_cascade_in_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='workspace',
            new_name='workspace_id',
        ),
    ]
