# Generated by Django 4.1.7 on 2023-03-28 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0018_change_field_name_from_workspace_to_workspace_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='workspace_id',
            field=models.ForeignKey(blank=True, db_column='workspace_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks_api.workspace'),
        ),
    ]
