# Generated by Django 4.1.7 on 2023-04-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0020_change_status_field_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='bgcolor',
            field=models.CharField(blank=True, default='806885', max_length=10),
        ),
    ]
